apiVersion: v1
kind: Service
metadata:
  name: scheduler
spec:
  type: LoadBalancer
  selector:
    app: scheduler
  ports:
    - name: nginx-http
      port: 80
      targetPort: 80
    - name: nginx-https
      port: 443
      targetPort: 443
